# Generated by Django 4.1.5 on 2023-03-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horaDeInicio', models.TimeField(verbose_name='hora de início')),
                ('descricao', models.CharField(max_length=100)),
                ('duracao', models.CharField(max_length=150)),
                ('horaDeTermino', models.TimeField(verbose_name='hora de término')),
            ],
        ),
    ]
